<program> ::= <function>
<function> ::= "int" <id> "(" ")" "{" <statement> "}"
<statement> ::= "return" <exp> ";"
<exp> ::= <int>

// tok = tokens.next()
    // if tok.type != "RETURN_KEYWORD":
    //     fail()
    // tok = tokens.next()
    // if tok.type != "INT"
    //     fail()
    // exp = parse_exp(tokens) //parse_exp will pop off more tokens
    // statement = Return(exp)

    // tok = tokens.next()
    // if tok.type != "SEMICOLON":
    //     fail()

    // return statement